### ISSUE TITLE
Received fatal alert: handshake_failure

### ISSUE THREAD

**Issue by the-fine** [paypal/permissions-sdk-java#5]
I'm using latest permission sdk and java 8.
I'm getting the following error when making the getBasicPersonalData call: Received fatal alert: handshake_failure

**Comment by jaypatel512** [comment]
Hey @the-fine !

We did update our `sdk-core-java` library to fix TLS issue, which I think you are seeing. Please make sure, you have version `sdk-core-java:1.7.0` or higher in your classpath.

Please re-open if you are still seeing this issue.
